use anyhow::Result;
use oxdock_core::{CommandMeta, all_metadata, all_structural_metadata};
use std::collections::HashSet;
#[allow(clippy::disallowed_types)]
use std::path::Path;

#[allow(clippy::disallowed_methods, clippy::disallowed_types)]
pub fn generate(output: &Path) -> Result<()> {
    let body = generate_body();
    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(output, body)?;
    Ok(())
}

/// Generate the command index table (mapped to its output file via the
/// `command-ref` provider's `command_index` fragment) from the
/// same metadata registry as the reference body, so the index can never
/// list a removed command (e.g. the stale `RUN_BG` row) or miss a new one.
#[allow(clippy::disallowed_methods, clippy::disallowed_types)]
pub fn generate_index(output: &Path) -> Result<()> {
    let out = render_index();
    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(output, out)?;
    Ok(())
}

pub(crate) fn render_index() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by docs-gen from oxdock-parser metadata. Do not edit by hand. -->\n",
    );
    out.push_str("## Command Reference\n\n");
    out.push_str("| Command | Syntax |\n");
    out.push_str("| --- | --- |\n");
    for meta in all_metadata() {
        out.push_str(&format!(
            "| [`{}`](#{}) | `{}` |\n",
            meta.name,
            index_anchor(meta.name),
            escape_table_cell(meta.syntax),
        ));
    }
    out
}

/// GitHub heading anchor for a `### NAME` section: lowercase. Command names
/// are `[A-Z_]+`, so lowercasing is the whole transformation.
fn index_anchor(name: &str) -> String {
    name.to_lowercase()
}

/// Escape pipe characters so `|` alternatives in syntax strings do not
/// break the enclosing Markdown table.
fn escape_table_cell(s: &str) -> String {
    s.replace('|', "\\|")
}

pub(crate) fn generate_body() -> String {
    let mut out = String::new();

    // Structural constructs (parsed by PEG rules, documented via the
    // structural registry in oxdock-parser — never hardcoded here).
    let structural = all_structural_metadata();
    let structural_names: HashSet<&str> = structural.iter().map(|meta| meta.name).collect();
    for meta in &structural {
        out.push_str(&render_meta(meta));
    }

    // Leaf commands (from declare_commands! metadata), excluding anything
    // already rendered above so every entry appears exactly once.
    for meta in all_metadata() {
        if structural_names.contains(meta.name) {
            continue;
        }
        out.push_str(&render_meta(&meta));
    }
    out
}

fn render_meta(meta: &CommandMeta) -> String {
    let mut out = String::new();
    out.push_str(&format!("### {}\n\n", meta.name));
    out.push_str(&format!("{}\n\n", meta.summary));
    out.push_str(&format!("**Syntax:** `{}`\n\n", meta.syntax));

    if !meta.description.is_empty() {
        out.push_str(&format!("{}\n\n", meta.description));
    }

    if !meta.args.is_empty() {
        out.push_str("**Arguments:**\n\n");
        out.push_str("| Name | Type | Required | Description |\n");
        out.push_str("| --- | --- | --- | --- |\n");
        for arg in meta.args {
            let req = if arg.required { "yes" } else { "no" };
            // Escape pipes so `|` alternations in type strings (e.g.
            // `SNAPSHOT|LOCAL`) cannot split the row into extra columns
            // on renderers without GitHub's code-span table handling.
            out.push_str(&format!(
                "| `{}` | `{}` | {} | {} |\n",
                escape_table_cell(arg.name),
                escape_table_cell(arg.arg_type),
                req,
                escape_table_cell(arg.description)
            ));
        }
        out.push('\n');
    }

    if !meta.flags.is_empty() {
        out.push_str("**Flags:**\n\n");
        out.push_str("| Flag | Type | Description |\n");
        out.push_str("| --- | --- | --- |\n");
        for flag in meta.flags {
            out.push_str(&format!(
                "| `{}` | {:?} | {} |\n",
                escape_table_cell(flag.long),
                flag.value_type,
                escape_table_cell(flag.description)
            ));
        }
        out.push('\n');
    }

    if let Some(stream) = meta.default_output {
        out.push_str(&format!("**Output:** {:?}\n\n", stream));
    }

    if !meta.examples.is_empty() {
        out.push_str("**Examples:**\n\n");
        for example in meta.examples {
            out.push_str(&format!("**Example: {}**\n\n", example.name));
            let fence = example
                .fence_meta
                .map_or_else(|| "oxdock".to_string(), |m| format!("oxdock {m}"));
            out.push_str(&format!(
                "```{}\n{}\n```\n\n",
                fence,
                example.code.trim_end()
            ));
        }
    }

    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn body_has_all_commands() {
        let body = generate_body();
        for meta in all_metadata() {
            assert!(
                body.contains(&format!("### {}", meta.name)),
                "missing section for command {}",
                meta.name
            );
        }
    }

    #[test]
    fn body_has_structural_constructs() {
        // Derived from the registry — not a hardcoded list — so adding a
        // structural entry automatically extends this check.
        let body = generate_body();
        for meta in all_structural_metadata() {
            assert!(
                body.contains(&format!("### {}", meta.name)),
                "missing section for structural construct {}",
                meta.name
            );
        }
    }
    #[test]
    fn metadata_names_are_unique() {
        // A command registered in both the leaf and structural registries
        // would render twice (or be shadowed by the skip filter). Structural
        // entries must live in exactly one registry.
        let mut seen = HashSet::new();
        for meta in all_metadata() {
            assert!(
                seen.insert(meta.name),
                "duplicate metadata entry for {}",
                meta.name
            );
        }
    }

    #[test]
    fn escape_table_cell_escapes_pipes() {
        assert_eq!(
            escape_table_cell("WORKSPACE SNAPSHOT|LOCAL"),
            "WORKSPACE SNAPSHOT\\|LOCAL"
        );
        assert_eq!(escape_table_cell("RUN <command...>"), "RUN <command...>");
    }

    #[test]
    fn index_lists_every_command_exactly_once() {
        // The index table is the drift detector for the command list: a
        // removed command must disappear and a new one must appear, with no
        // hand-maintained rows to forget.
        let body = render_index();
        for meta in all_metadata() {
            let row = format!("| [`{}`](#{}) |", meta.name, index_anchor(meta.name));
            assert!(
                body.matches(&row).count() == 1,
                "index must list {} exactly once",
                meta.name
            );
        }
        assert!(
            !body.contains("RUN_BG"),
            "index must not contain removed commands"
        );
    }
}
